language: node_js
os:
  - linux
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: PRETEST=true
    - node_js: "lts/*"
      env: BUILD=true